### ISSUE TITLE
Rage Trade - Incorrect "maxAvailable" calc in "maxWithdraw" for Senior Vault

### ISSUE THREAD

**Issue by jacksanford1** [sherlock-audit/2022-10-rage-trade-judging#84]
0x52

RageTrade (found by protocol team after contest)

medium

# In "maxWithdraw" for Senior Vault, the calculation for "maxAvailable" was incorrect.

## Summary

In "maxWithdraw" for Senior Vault, the calculation for "maxAvailable" was incorrect.

## Impact

Could result in unexpected behavior

## Code Snippet

https://github.com/sherlock-audit/2022-10-rage-trade/blob/main/dn-gmx-vaults/contracts/vaults/DnGmxSeniorVault.sol#L406

## Tool used

Manual Review

## Recommendation

Fixed by RageTrade in [PR #50](https://github.com/RageTrade/delta-neutral-gmx-vaults/pull/50)

**Comment by 0x00052** [comment]
Fix looks good. Old math would underestimate available withdraw. New math fixes this
